import { OllAlg } from '../oll-alg';

export const OllAlgs: OllAlg[] = [
  { id: 1, name: 'alg1', 'src': 'assets/oll-pics/1.svg', type: 'dot' },
  { id: 2, name: 'alg2', 'src': 'assets/oll-pics/2.svg', type: 'dot' },
  { id: 3, name: 'alg3', 'src': 'assets/oll-pics/3.svg', type: 'dot' },
  { id: 4, name: 'alg4', 'src': 'assets/oll-pics/4.svg', type: 'dot' },
  { id: 5, name: 'alg5', 'src': 'assets/oll-pics/5.svg', type: 'square' },
  { id: 6, name: 'alg6', 'src': 'assets/oll-pics/6.svg', type: 'square' },
  { id: 7, name: 'alg7', 'src': 'assets/oll-pics/7.svg', type: 'lightning' },
  { id: 8, name: 'alg8', 'src': 'assets/oll-pics/8.svg', type: 'lightning' },
  { id: 9, name: 'alg9', 'src': 'assets/oll-pics/9.svg', type: 'fish' },
  { id: 10, name: 'alg10', 'src': 'assets/oll-pics/10.svg', type: 'fish' },
  { id: 11, name: 'alg11', 'src': 'assets/oll-pics/11.svg', type: 'lightning' },
  { id: 12, name: 'alg12', 'src': 'assets/oll-pics/12.svg', type: 'lightning' },
  { id: 13, name: 'alg13', 'src': 'assets/oll-pics/13.svg', type: 'knight move' },
  { id: 14, name: 'alg14', 'src': 'assets/oll-pics/14.svg', type: 'knight move' },
  { id: 15, name: 'alg15', 'src': 'assets/oll-pics/15.svg', type: 'knight move' },
  { id: 16, name: 'alg16', 'src': 'assets/oll-pics/16.svg', type: 'knight move' },
  { id: 17, name: 'alg17', 'src': 'assets/oll-pics/17.svg', type: 'dot' },
  { id: 18, name: 'alg18', 'src': 'assets/oll-pics/18.svg', type: 'dot' },
  { id: 19, name: 'alg19', 'src': 'assets/oll-pics/19.svg', type: 'dot' },
  { id: 20, name: 'alg20', 'src': 'assets/oll-pics/20.svg', type: 'dot' },
  { id: 21, name: 'alg21', 'src': 'assets/oll-pics/21.svg', type: 'edges oriented' },
  { id: 22, name: 'alg22', 'src': 'assets/oll-pics/22.svg', type: 'edges oriented' },
  { id: 23, name: 'alg23', 'src': 'assets/oll-pics/23.svg', type: 'edges oriented' },
  { id: 24, name: 'alg24', 'src': 'assets/oll-pics/24.svg', type: 'edges oriented' },
  { id: 25, name: 'alg25', 'src': 'assets/oll-pics/25.svg', type: 'edges oriented' },
  { id: 26, name: 'alg26', 'src': 'assets/oll-pics/26.svg', type: 'edges oriented' },
  { id: 27, name: 'alg27', 'src': 'assets/oll-pics/27.svg', type: 'edges oriented' },
  { id: 28, name: 'alg28', 'src': 'assets/oll-pics/28.svg', type: 'corners oriented' },
  { id: 29, name: 'alg29', 'src': 'assets/oll-pics/29.svg', type: 'awkward' },
  { id: 30, name: 'alg30', 'src': 'assets/oll-pics/30.svg', type: 'awkward' },
  { id: 31, name: 'alg31', 'src': 'assets/oll-pics/31.svg', type: 'p' },
  { id: 32, name: 'alg32', 'src': 'assets/oll-pics/32.svg', type: 'p' },
  { id: 33, name: 'alg33', 'src': 'assets/oll-pics/33.svg', type: 't' },
  { id: 34, name: 'alg34', 'src': 'assets/oll-pics/34.svg', type: 'c' },
  { id: 35, name: 'alg35', 'src': 'assets/oll-pics/35.svg', type: 'fish' },
  { id: 36, name: 'alg36', 'src': 'assets/oll-pics/36.svg', type: 'w' },
  { id: 37, name: 'alg37', 'src': 'assets/oll-pics/37.svg', type: 'fish' },
  { id: 38, name: 'alg38', 'src': 'assets/oll-pics/38.svg', type: 'w' },
  { id: 39, name: 'alg39', 'src': 'assets/oll-pics/39.svg', type: 'lightning' },
  { id: 40, name: 'alg40', 'src': 'assets/oll-pics/40.svg', type: 'lightning' },
  { id: 41, name: 'alg41', 'src': 'assets/oll-pics/41.svg', type: 'awkward' },
  { id: 42, name: 'alg42', 'src': 'assets/oll-pics/42.svg', type: 'awkward' },
  { id: 43, name: 'alg43', 'src': 'assets/oll-pics/43.svg', type: 'p' },
  { id: 44, name: 'alg44', 'src': 'assets/oll-pics/44.svg', type: 'p' },
  { id: 45, name: 'alg45', 'src': 'assets/oll-pics/45.svg', type: 't' },
  { id: 46, name: 'alg46', 'src': 'assets/oll-pics/46.svg', type: 'c' },
  { id: 47, name: 'alg47', 'src': 'assets/oll-pics/47.svg', type: 'l' },
  { id: 48, name: 'alg48', 'src': 'assets/oll-pics/48.svg', type: 'l' },
  { id: 49, name: 'alg49', 'src': 'assets/oll-pics/49.svg', type: 'l' },
  { id: 50, name: 'alg50', 'src': 'assets/oll-pics/50.svg', type: 'l' },
  { id: 51, name: 'alg51', 'src': 'assets/oll-pics/51.svg', type: 'line' },
  { id: 52, name: 'alg52', 'src': 'assets/oll-pics/52.svg', type: 'line' },
  { id: 53, name: 'alg53', 'src': 'assets/oll-pics/53.svg', type: 'l' },
  { id: 54, name: 'alg54', 'src': 'assets/oll-pics/54.svg', type: 'l' },
  { id: 55, name: 'alg55', 'src': 'assets/oll-pics/55.svg', type: 'line' },
  { id: 56, name: 'alg56', 'src': 'assets/oll-pics/56.svg', type: 'line' },
  { id: 57, name: 'alg57', 'src': 'assets/oll-pics/57.svg', type: 'corners oriented' }
];